export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST'
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS'
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL'
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET'

export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST'
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS'
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL'