// export const CONVERSATION_LIST_REQUEST = 'CONVERSATION_LIST_REQUEST'
// export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS'
// export const CONVERSATION_LIST_FAIL = 'CONVERSATION_LIST_FAIL'

// export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
// export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
// export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL'